name: flutter_clean_architecture
version: 1.0.0+1
description: Boilerplate Flutter project.

environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  auto_size_text: 3.0.0
  avatar_view: 1.0.1
  cached_network_image: 3.2.3
  connectivity_plus: 4.0.1
  dartz: 0.10.1
  device_info_plus: 9.0.2
  device_preview: 1.1.0
  dio: 5.2.1+1
  dio_cache_interceptor: 3.4.2
  dio_cache_interceptor_hive_store: 3.2.1
  drift: 2.8.0
  encrypt: 5.0.1
  encrypted_drift:
    git:
      url: https://github.com/simolus3/drift.git
      path: extras/encryption
  equatable: 2.0.5
  file_picker: 5.3.1
  firebase_auth: 4.6.3
  firebase_core: 2.14.0
  firebase_crashlytics: 3.3.3
  firebase_messaging: 14.6.4
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  flutter_jailbreak_detection: 1.10.0
  flutter_local_notifications: 14.1.1
  flutter_localization: 0.1.12
  flutter_secure_storage: 8.0.0
  flutter_svg: 2.0.5
  fluttertoast: 8.2.2
  get_it: 7.6.0
  hive: 2.2.3
  hive_flutter: 1.1.0
  hive_generator: 2.0.0
  image_picker: 1.0.0
  intl: 0.17.0
  logger: 1.4.0
  logging: 1.2.0
  open_filex: 4.3.2
  package_info_plus: 4.0.2
  path_provider: 2.0.15
  permission_handler: 10.4.0
  share_plus: 7.0.2
  shared_preferences: 2.1.2
  shimmer: 3.0.0
  sign_in_with_apple: 5.0.0
  store_redirect: 2.0.1
  super_tooltip: ^1.0.1
  url_launcher: 6.1.11
  webview_flutter: 3.0.1


dev_dependencies: 
  build_runner: 2.3.3
  drift_dev: 2.8.0
  flutter_gen_runner: 5.3.1
  flutter_launcher_icons: 0.13.1
  flutter_test:
    sdk: flutter
  pubspec_dependency_sorter: 1.0.3
  retrofit_generator: 7.0.7

#  Replace launcher_icon.png file according to project at "assets/images/launcher/launcher_icon.png" path
#  Execute "flutter clean" command in terminal
#  Execute "flutter pub get" command in terminal
#  Execute "flutter pub run flutter_launcher_icons" command in terminal

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/launcher/launcher_icon.png"

flutter:
  uses-material-design: true

  assets:
    - lang/
    - assets/images/icons/
    - assets/images/splash/
    - assets/images/app_logo/
    - assets/mock_json/

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/MulishBold.ttf
          weight: 700
        - asset: assets/fonts/MulishSemiBold.ttf
          weight: 600
        - asset: assets/fonts/MulishMedium.ttf
          weight: 500

