const String KEY_FCM_ID = "KEY_FCM_ID";
const String KEY_DEVICE_ID = "KEY_DEVICE_ID";
const String KEY_FIRSTNAME = "KEY_FIRSTNAME";
const String KEY_LASTNAME = "KEY_LASTNAME";
const String KEY_COUNTRY_CODE = "KEY_COUNTRY_CODE";
const String KEY_DEVICE_TOKEN = "KEY_DEVICE_TOKEN";
const String KEY_MOBILE_NO = "KEY_MOBILE_NO";
const String KEY_EMAIL = "KEY_EMAIL";
const String KEY_COUNTRY_NAME = "KEY_COUNTRY_NAME";
const String KEY_CITY_NAME = "KEY_CITY_NAME";
const String KEY_MEMBERSHIP_NUMBER = "KEY_MEMBERSHIP_NUMBER";
const String KEY_PASSWORD = "KEY_PASSWORD";
const String KEY_AUTHENTICATION_TOKEN = "KEY_AUTHENTICATION_TOKEN";
const String KEY_IS_MULAKAT = "KEY_IS_MULAKAT";
const String KEY_USER_LOGGED_IN = "KEY_USER_LOGGED_IN";
const String KEY_SHOW_DARBAR_COUNTRYCITYREPORT =
    "KEY_SHOW_DARBAR_COUNTRYCITYREPORT";
const String KEY_SHOW_DARBAR_INTERNATIONCOUNTRYCITYREPORT =
    "KEY_SHOW_DARBAR_INTERNATIONCOUNTRYCITYREPORT";
const String KEY_SHOW_DARBAR_AGEGROUPREPORT = "KEY_SHOW_DARBAR_AGEGROUPREPORT";
const String KEY_SHOW_SCHOOL_MANAGEMENT = "KEY_SHOW_SCHOOL_MANAGEMENT";
const String KEY_SHOW_DARBAR_INTERNATIONAGEGROUPREPORT =
    "KEY_SHOW_DARBAR_INTERNATIONAGEGROUPREPORT";
const String KEY_SHOW_DARBAR_REGISTRATIONREPORT =
    "KEY_SHOW_DARBAR_REGISTRATIONREPORT";
const String KEY_SHOW_LOUNGE_CHECKIN = "KEY_SHOW_LOUNGE_CHECKIN";
const String KEY_SHOW_DARBAR_HALLCHECKIN = "KEY_SHOW_DARBAR_HALLCHECKIN";
const String KEY_SHOW_DARBAR_HALLCHECKOUT = "KEY_SHOW_DARBAR_HALLCHECKOUT";
const String KEY_BULLETIN_HTML_DATA = "KEY_BULLETIN_HTML_DATA";
const String KEY_HOTLINE_HTML_DATA = "KEY_HOTLINE_HTML_DATA";
const String KEY_APP_UPDATE_DELAYED_TIME = "KEY_APP_UPDATE_DELAYED_TIME";
const String KEY_APP_THEME = "KEY_APP_THEME";
const String KEY_SCHOOL_ID = "KEY_SCHOOL_ID";
const String KEY_PERMISSION_ASKED_FOR_NORMAL_CAL =
    "KEY_PERMISSION_ASKED_FOR_NORMAL_CAL";
const String KEY_PERMISSION_ASKED_FOR_MAJALIS_CAL =
    "KEY_PERMISSION_ASKED_FOR_MAJALIS_CAL";
